apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: home-assistant-jz-c-org
  namespace: default
  annotations:
    domain: home-assistant.jz-c.org
spec:
  secretName: production-home-assistant-jz-c-org-tls
  commonName: home-assistant.jz-c.org
  dnsNames:
  - home-assistant.jz-c.org
  issuerRef:
    name: production-letsencrypt
    kind: ClusterIssuer
