apiVersion: v1
kind: PersistentVolume
metadata:
  name: urbackup-backups
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_4tb/k8s/volumes/urbackup/urbackup/backups
    server: proxmox.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: urbackup-database
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/urbackup/urbackup/database
    server: proxmox.zhc.x64.me
