---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nextcloud.jz-c.org-cert
  namespace: default
spec:
  secretName: nextcloud.jz-c.org-tls
  issuerRef:
    name: letsencrypt-production-issuer
  commonName: nextcloud.jz-c.org
  dnsNames:
  - nextcloud.jz-c.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - nextcloud.jz-c.org
---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: office.jz-c.org-cert
  namespace: default
spec:
  secretName: office.jz-c.org-tls
  issuerRef:
    name: letsencrypt-production-issuer
  commonName: office.jz-c.org
  dnsNames:
  - office.jz-c.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - office.jz-c.org
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-secure-backends
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16G"
spec:
  tls:
  - hosts:
    - nextcloud.jz-c.org
    secretName: nextcloud.jz-c.org-tls
  - hosts:
    - office.jz-c.org
    secretName: office.jz-c.org-tls
  rules:
  - host: nextcloud.jz-c.org
    http:
      paths:
      - backend:
          serviceName: nextcloud-service
          servicePort: 443
  - host: office.jz-c.org
    http:
      paths:
      - backend:
          serviceName: collabora-service
          servicePort: 443
