apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-data
          nfs:
            server: storage.zhc.x64.me
            path: /mnt/datacenter_250GB/kubernetes/development/nextcloud/data
      containers:
        - name: nextcloud
          image: nextcloud:12.0.1-apache
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-mariadb
  template:
    metadata:
      labels:
        app: nextcloud-mariadb
    spec:
      volumes:
        - name: nextcloud-mariadb
          nfs:
            server: storage.zhc.x64.me
            path: /mnt/datacenter_250GB/kubernetes/development/nextcloud/mariadb
      containers:
        - name: nextcloud-mariadb
          image: mariadb:10.3.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 01928375jk1h5125
          volumeMounts:
            - name: nextcloud-mariadb
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mariadb-service
spec:
  selector:
    app: nextcloud-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
