---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - image: "linuxserver/nextcloud:112"
          name: nextcloud
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /data
              name: nextcloud-data-volume
            - mountPath: /config
              name: nextcloud-config-volume
      volumes:
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        - name: nextcloud-config-volume
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-mariadb
  template:
    metadata:
      labels:
        app: nextcloud-mariadb
    spec:
      containers:
        - name: nextcloud-mariadb
          image: mariadb:10.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 01928375jk1h5125
          volumeMounts:
            - name: mariadb-data-volume
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mariadb-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-mariadb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-config-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/nextcloud/data
    server: storage.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/nextcloud/config
    server: storage.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-mariadb-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/nextcloud/mariadb
    server: storage.zhc.x64.me
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mariadb-service
spec:
  selector:
    app: nextcloud-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
