apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
      - name: influxdb
        env:
        - name: INFLUXDB_DB
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_DB
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_ADMIN_USER
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_ADMIN_PASSWORD
        - name: INFLUXDB_WRITE_USER
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_WRITE_USER
        - name: INFLUXDB_WRITE_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_WRITE_USER_PASSWORD
        - name: INFLUXDB_READ_USER
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_READ_USER
        - name: INFLUXDB_READ_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_READ_USER_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitfinex-crawler
spec:
  template:
    spec:
      initContainers:
      - name: init-influxdb
        image: curl
        command: ["sh", "-c", "until curl -sL -I $(INFLUXDB_SERVICE):8086/ping; do echo waiting for $(INFLUXDB_SERVICE); sleep 2; done;"]
      containers:
      - name: bitfinex-crawler
        env:
        - name: INFLUXDB_HOST
          value: "$(INFLUXDB_SERVICE)"
        - name: INFLUXDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_DB
        - name: INFLUXDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_WRITE_USER
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_WRITE_USER_PASSWORD
