---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-media
  labels:
    app: motioneye
    component: motioneye
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_4TB/k8s/volumes/motioneye/motioneye/media
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-config
  labels:
    app: motioneye
    component: motioneye
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/motioneye/motioneye/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-media
  labels:
    app: motioneye
    component: motioneye
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: motioneye-media
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-config
  labels:
    app: motioneye
    component: motioneye
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: motioneye-config
---

apiVersion: v1
kind: Service
metadata:
  name: motioneye
  labels:
    app: motioneye
    component: motioneye
    tier: frontend
spec:
  selector:
    app: motioneye
    component: motioneye
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8765
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye
  labels:
    app: motioneye
    component: motioneye
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motioneye
      component: motioneye
      tier: frontend
  template:
    metadata:
      labels:
        app: motioneye
        component: motioneye
        tier: frontend
    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: motioneye-media
        - name: config
          persistentVolumeClaim:
            claimName: motioneye-config
      containers:
        - image: ccrisan/motioneye:0.40-amd64
          name: motioneye
          env:
            - name: TIMEZONE
              value: "Europe/Berlin"
          volumeMounts:
            - name: media
              mountPath: /var/lib/motioneye
            - name: config
              mountPath: /etc/motioneye
          ports:
            - containerPort: 8765
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
