apiVersion: apps/v1
kind: Deployment
metadata:
  name: motioneye
spec:
  template:
    spec:
      containers:
      - name: motioneye
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
