apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    component: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nextcloud
  template:
    metadata:
      labels:
        component: nextcloud
    spec:
      volumes:
      - name: nginx
        configMap:
          name: fpm-nextcloud
      - name: html
        emptyDir: {}
      - name: custom-apps
        emptyDir: {}
      - name: config
        emptyDir: {}
      - name: data
        emptyDir: {}
      containers:
      - name: nextcloud
        image: nextcloud-fpm
        volumeMounts:
        - name: html
          mountPath: /var/www/html
        - name: custom-apps
          mountPath: /var/www/html/custom_apps
        - name: config
          mountPath: /var/www/html/config
        - name: data
          mountPath: /var/www/html/data
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/conf.d
        - name: html
          mountPath: /var/www/html
        - name: custom-apps
          mountPath: /var/www/html/custom_apps
          readOnly: true
        - name: config
          mountPath: /var/www/html/config
          readOnly: true
        - name: data
          mountPath: /var/www/html/data
          readOnly: true
        ports:
        - containerPort: 80
