---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/home-assistant/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-config-pv
---

apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
spec:
  selector:
    app: home-assistant
  ports:
  - name: web-interface
    protocol: TCP
    port: 8123
    targetPort: 8123
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      volumes:
      - name: home-assistant-config-volume
        persistentVolumeClaim:
          claimName: home-assistant-config-pvc
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:0.74.2
        volumeMounts:
        - name: home-assistant-config-volume
          mountPath: /config
        ports:
        - containerPort: 8123
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
