---

apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-mariadb-root-user
type: Opaque
data:
  username: cm9vdAo=
  password: WFIyNHdiYlp0QzdXbTRqRAo=
---

apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-mariadb-homeassistant-user
type: Opaque
data:
  username: aG9tZWFzc2lzdGFudAo=
  password: ZTIwSVhyeWlicml1NEszbAo=
