apiVersion: v1
kind: Service
metadata:
  name: node-red
  labels:
    component: node-red
spec:
  selector:
    component: node-red
  ports:
  - name: web-interface
    protocol: TCP
    port: 80
    targetPort: 1880
