apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "$(NEXTCLOUD_SERVICE_IP)"
