---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mayan-edms-media-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/mayan-edms/media
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayan-edms-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: mayan-edms-media-pv
---

apiVersion: v1
kind: Service
metadata:
  name: mayan-edms-service
spec:
  selector:
    app: mayan-edms
  ports:
  - name: web-interface
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 192.168.1.249
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayan-edms
  labels:
    app: mayan-edms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayan-edms
  template:
    metadata:
      labels:
        app: mayan-edms
    spec:
      volumes:
      - name: mayan-edms-media-volume
        persistentVolumeClaim:
          claimName: mayan-edms-media-pvc
      containers:
      - name: mayan-edms
        image: mayanedms/mayanedms:3.0.1
        env:
          - name: MAYAN_DATABASE_ENGINE
            value: django.db.backends.mysql
          - name: MAYAN_DATABASE_HOST
            value: mayan-edms-mariadb-service
          - name: MAYAN_DATABASE_NAME
            value: mayan
          - name: MAYAN_DATABASE_USER
            value: mayan
          - name: MAYAN_DATABASE_PASSWORD
            value: RCT30OTDISsiZWDg
          - name: MAYAN_DATABASE_CONN_MAX_AGE
            value: "60"
          - name: MAYAN_APT_INSTALLS
            value: tesseract-ocr-deu
          - name: MAYAN_DOCUMENTS_FIX_ORIENTATION
            value: "false"
          - name: MAYAN_DOCUMENTS_LANGUAGE
            value: "deu"
        volumeMounts:
        - name: mayan-edms-media-volume
          mountPath: /var/lib/mayan
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "125m"
            memory: "256Mi"
