apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
      - name: influxdb
        env:
        - name: INFLUXDB_DB
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_DB
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_ADMIN_USER
        - name: INFLUXDB_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_ADMIN_PASSWORD
        - name: INFLUXDB_WRITE_USER
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_WRITE_USER
        - name: INFLUXDB_WRITE_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_WRITE_USER_PASSWORD
        - name: INFLUXDB_READ_USER
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_READ_USER
        - name: INFLUXDB_READ_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: INFLUXDB_READ_USER_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  template:
    spec:
      initContainers:
      - name: init-influxdb
        image: appropriate/curl
        command: ["sh", "-c", "until curl -sL -I home-assistant-influxdb:8086/ping; do echo waiting for home-assistant-influxdb; sleep 2; done;"]
