apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: freenas-nfs-storage
parameters:
  mountOptions: "vers=3.0,nfsvers=3,version=3"
mountOptions:
  - vers=3.0
  - nfsvers=3
  - version=3
provisioner: storage.zcc.x64.me/persistent-volumes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v2.0.1
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: storage.zcc.x64.me/persistent-volumes
            - name: NFS_SERVER
              value: storage.zcc.x64.me
            - name: NFS_PATH
              value: /mnt/datacenter_250GB/kubernetes/development/persistent-volumes
      volumes:
        - name: nfs-client-root
          nfs:
            server: storage.zcc.x64.me
            path: /mnt/datacenter_250GB/kubernetes/development/persistent-volumes
