resources:
  - nextcloud/deployment.yaml
  - nextcloud/service.yaml
  - mariadb/deployment.yaml
  - mariadb/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
patchesStrategicMerge:
  - patches/nextcloud.yaml
  - patches/mariadb.yaml
  - patches/redis.yaml
vars:
  - name: MARIADB_SERVICE
    objref:
      kind: Service
      name: mariadb
      apiVersion: v1
  - name: REDIS_SERVICE
    objref:
      kind: Service
      name: redis
      apiVersion: v1
