bases:
- ../base
patchesStrategicMerge:
- patches/set_domain.yaml
resources:
- resources/certificate.yaml
- resources/ingress.yaml
namePrefix: testing-bitwarden-
commonLabels:
  app: bitwarden
  env: testing
images:
- name: bitwarden
  newName: bitwardenrs/server
  newTag: 1.9.1-alpine
vars:
- name: BITWARDEN_INGRESS_DOMAIN
  objref:
    kind: Certificate
    name: test-jz-c-org-production
    apiVersion: certmanager.k8s.io/v1alpha1
  fieldref:
    fieldpath: metadata.annotations.domain
