apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: motioneye-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motioneye-config
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: motioneye-config
