apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-media
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_4tb/k8s/volumes/motioneye/motioneye/media
    server: proxmox.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/motioneye/motioneye/config
    server: proxmox.zhc.x64.me
