apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: onlyoffice
        image: onlyoffice/documentserver:latest
        ports:
         - containerPort: 80
