apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-config
  labels:
    app: unifi
    component: unifi
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/unifi/unifi/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  labels:
    app: unifi
    component: unifi
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: unifi-config
---

apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
  labels:
    app: unifi
    component: unifi
    tier: frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi"
spec:
  selector:
    app: unifi
    component: unifi
    tier: frontend
  ports:
  - name: device-command
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: web-interface
    protocol: TCP
    port: 443
    targetPort: 8443
  - name: https-portal
    protocol: TCP
    port: 8843
    targetPort: 8843
  - name: http-portal
    protocol: TCP
    port: 8880
    targetPort: 8880
  - name: speed-test
    protocol: TCP
    port: 6789
    targetPort: 6789
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.5

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp
  labels:
    app: unifi
    component: unifi
    tier: frontend
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi"
spec:
  selector:
    app: unifi
    component: unifi
    tier: frontend
  ports:
  - name: stun-service
    protocol: UDP
    port: 3478
    targetPort: 3478
  - name: ubnt-discovery
    protocol: UDP
    port: 10001
    targetPort: 10001
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  labels:
    app: unifi
    component: unifi
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
      component: unifi
      tier: frontend
  template:
    metadata:
      labels:
        app: unifi
        component: unifi
        tier: frontend
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: unifi-config
      containers:
      - name: unifi
        image: jacobalberty/unifi:5.9
        env:
          - name: TZ
            value: Europe/Berlin
        volumeMounts:
          - name: config
            mountPath: /unifi
        ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 8843
          - containerPort: 8880
          - containerPort: 6789
          - containerPort: 3478
            protocol: UDP
          - containerPort: 10001
            protocol: UDP
        resources:
          limits:
            cpu: "250m"
            memory: "1024Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
