apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    component: mariadb
spec:
  replicas: 1
  selector:
      matchLabels:
        component: mariadb
  template:
    metadata:
      labels:
        component: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
