---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-collabora
  labels:
    app: nextcloud
    component: collabora
    tier: frontend
spec:
  selector:
    app: nextcloud
    component: collabora
    tier: frontend
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9980
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-collabora
  labels:
    app: nextcloud
    component: collabora
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: collabora
      tier: frontend
  template:
    metadata:
      labels:
        app: nextcloud
        component: collabora
        tier: frontend
    spec:
      containers:
      - name: nextcloud-collabora
        image: collabora/code:4.0.0.1
        env:
        - name: domain
          value: "nextcloud\\.jz-c\\.org|test\\.jz-c\\.org"
        ports:
        - containerPort: 9980
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
