---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-collabora
  labels:
    app: nextcloud
    component: collabora
    tier: frontend
spec:
  selector:
    app: nextcloud
    component: collabora
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9980
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-collabora
  labels:
    app: nextcloud
    component: collabora
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: collabora
      tier: frontend
  template:
    metadata:
      labels:
        app: nextcloud
        component: collabora
        tier: frontend
    spec:
      containers:
      - name: nextcloud-collabora
        image: collabora/code:4.0.3.1
        env:
        - name: domain
          value: "nextcloud\\.jz-c\\.org"
        - name: server_name
          value: "office.jz-c.org"
        - name: DONT_GEN_SSL_CERT
          value: "true"
        - name: extra_params
          value: "--o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host[0]=::ffff:10\\.233\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\} --o:net.post_allow.host[1]=10\\.233\\.[0-9]\\{1,3\\}\\.[0-9]\\{1,3\\}"
        ports:
        - containerPort: 9980
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - MKNOD
