---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-mariadb-data
  labels:
    app: nextcloud
    component: mariadb
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/nextcloud/mariadb/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-mariadb-data
  labels:
    app: nextcloud
    component: mariadb
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-mariadb-data
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud
    component: mariadb
    tier: database
spec:
  selector:
    app: nextcloud
    component: mariadb
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nextcloud-mariadb
  labels:
    app: nextcloud
    component: mariadb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: mariadb
      tier: database
  template:
    metadata:
      labels:
        app: nextcloud
        component: mariadb
        tier: database
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-mariadb-data
      containers:
        - name: nextcloud-mariadb
          image: mariadb:10.3.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-root-user
                  key: password
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-nextcloud-user
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-nextcloud-user
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
