---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-onlyoffice
  labels:
    app: nextcloud
    component: onlyoffice
spec:
  selector:
    app: nextcloud
    component: onlyoffice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-onlyoffice
  labels:
    app: nextcloud
    component: onlyoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: onlyoffice
  template:
    metadata:
      labels:
        app: nextcloud
        component: onlyoffice
    spec:
      containers:
      - image: onlyoffice/documentserver:5.2.8.24
        name: onlyoffice
        env:
          - name: JWT_ENABLED
            value: "true"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: nextcloud.onlyoffice
                key: jwt-secret
        ports:
         - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
