---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis-data
  labels:
    app: nextcloud
    component: redis
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/nextcloud/redis/data
    server: proxmox.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis-data
  labels:
    app: nextcloud
    component: redis
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-redis-data
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-redis
  labels:
    app: nextcloud
    component: redis
    tier: cache
spec:
  selector:
    app: nextcloud
    component: redis
    tier: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-redis
  labels:
    app: nextcloud
    component: redis
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: redis
      tier: cache
  template:
    metadata:
      labels:
        app: nextcloud
        component: redis
        tier: cache
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-redis-data
      containers:
        - image: redis:4.0.9-alpine
          name: nextcloud-redis
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
