apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    component: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: influxdb-data
      containers:
      - name: influxdb
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb
