apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitfinex-crawler
spec:
  template:
    spec:
      containers:
      - name: bitfinex-crawler
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  template:
    spec:
      containers:
      - name: influxdb
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
