apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp
  labels:
    app: replica-testing
    component: webserver
    env: testing
spec:
  selector:
    app: replica-testing
    component: webserver
    env: testing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.100
