---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus.graphite-mapping
  namespace: monitoring
  labels:
    app: prometheus
    component: freenas-exporter
data:
  graphite_mapping.conf: |-
    # servers.storage_zcc_x64_me.df-mnt-datacenter_1tb.df_complex-used
    mappings:
    - match: servers\.(.+)\.df\-mnt\-(.+)\.df_(.+)
      match_type: regex
      name: freenas_df
      labels:
        instance: $1
        dataset: $2
        type: $3

    - match: servers.*.aggregation-cpu-average.*
      name: freenas_aggregation_cpu_average
      labels:
        instance: $1
        states: $2

    - match: servers.*.aggregation-cpu-max.*
      name: freenas_aggregation_cpu_max
      labels:
        instance: $1
        states: $2

    - match: servers.*.aggregation-cpu-min.*
      name: freenas_aggregation_cpu_min
      labels:
        instance: $1
        states: $2

    - match: servers.*.aggregation-cpu-num.*
      name: freenas_aggregation_cpu_num
      labels:
        instance: $1
        states: $2

    - match: servers.*.aggregation-cpu-stddev.*
      name: freenas_aggregation_cpu_stddev
      labels:
        instance: $1
        states: $2

    - match: servers.*.aggregation-cpu-sum.*
      name: freenas_aggregation_cpu_sum
      labels:
        instance: $1
        states: $2

    - match: servers\.(.+)\.cpu\-(\d)\.(.+)
      match_type: regex
      name: freenas_cpu
      labels:
        instance: $1
        num: $2
        states: $3

    - match: servers.*.zfs_arc.*
      name: freenas_zfs_arc
      labels:
        instance: $1
        stat: $2

    - match: servers.*.zfs_arc_v2.*
      name: freenas_zfs_arc_v2
      labels:
        instance: $1
        stat: $2

    - match: servers.*.swap.*
      name: freenas_swap
      labels:
        instance: $1
        type: $2

    - match: servers.*.uptime.uptime
      name: freenas_uptime
      labels:
        instance: $1

    - match: servers.*.processes.*
      name: freenas_processes
      labels:
        instance: $1
        state: $2

    - match: servers.*.memory.*
      name: freenas_memory
      labels:
        instance: $1
        class: $2

    - match: servers.*.load.load.*
      name: freenas_load
      labels:
        instance: $1
        type: $2

    - match: servers\.(.+)\.disk\-(.+)\.((.+)\.(.+))
      match_type: regex
      name: freenas_disk
      labels:
        instance: $1
        disk: $2
        stat: $3

    - match: servers\.(.+)\.geom_stat\.geom_ops\-(.+)
      match_type: regex
      name: freenas_geom_ops
      labels:
        instance: $1
        disk: $2

    - match: servers\.(.+)\.geom_stat\.geom_busy_percent\-(.+)
      match_type: regex
      name: freenas_geom_busy_percent
      labels:
        instance: $1
        disk: $2

    - match: servers\.(.+)\.geom_stat\.geom_queue\-(.+)
      match_type: regex
      name: freenas_geom_queue
      labels:
        instance: $1
        disk: $2

    - match: servers\.(.+)\.geom_stat\.geom_bw\-(.+)\.(.+)
      match_type: regex
      name: freenas_geom_bw
      labels:
        instance: $1
        disk: $2
        operation: $3

    - match: servers\.(.+)\.geom_stat\.geom_latency\-(.+)\.(.+)
      match_type: regex
      name: freenas_geom_latency
      labels:
        instance: $1
        disk: $2
        operation: $3

    - match: servers\.(.+)\.geom_stat\.geom_ops_rwd\-(.+)\.(.+)
      match_type: regex
      name: freenas_geom_ops_rwd
      labels:
        instance: $1
        disk: $2
        operation: $3

    - match: servers\.(.+)\.interface\-(.+)\.if_errors\.(.+)
      match_type: regex
      name: freenas_interface_errors
      labels:
        instance: $1
        interface: $2
        direction: $3

    - match: servers\.(.+)\.interface\-(.+)\.if_octets\.(.+)
      match_type: regex
      name: freenas_interface_octets
      labels:
        instance: $1
        interface: $2
        direction: $3

    - match: servers\.(.+)\.interface\-(.+)\.if_packets\.(.+)
      match_type: regex
      name: freenas_interface_packets
      labels:
        instance: $1
        interface: $2
        direction: $3

    - match: servers\.(.+)\.ctl-ioctl\.(.*)\.(.*)
      match_type: regex
      name: freenas_ctl_ioctl
      labels:
        instance: $1
        stat: $2
        operation: $3

    - match: servers\.(.+)\.ctl-tpc\.(.*)\.(.*)
      match_type: regex
      name: freenas_ctl_tpc
      labels:
        instance: $1
        stat: $2
        operation: $3
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-freenas-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: freenas-exporter
spec:
  selector:
    app: prometheus
    component: freenas-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9108
      targetPort: 9108
    - name: graphite-ingestion
      protocol: TCP
      port: 2003
      targetPort: 9109
  type: LoadBalancer
  loadBalancerIP: 192.168.1.223
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-freenas-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: freenas-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: freenas-exporter
  template:
    metadata:
      labels:
        app: prometheus
        component: freenas-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '9108'
    spec:
      volumes:
        - name: config
          configMap:
            name: prometheus.graphite-mapping
      containers:
        - image: prom/graphite-exporter:v0.4.2
          name: freenas-exporter
          args:
            - --graphite.mapping-strict-match
            - --graphite.mapping-config=/tmp/graphite_mapping.conf
          volumeMounts:
            - name: config
              mountPath: /tmp
          ports:
            - containerPort: 9108
            - containerPort: 9109
