---

apiVersion: v1
kind: Secret
metadata:
  name: prometheus.mysql-exporter.data-source-name
  namespace: monitoring
type: Opaque
data:
  # prometheus:PASSWORD@(localhost:3306)/
  data-source-name: cHJvbWV0aGV1czpGbXAyREdGSUR0RURTMkAobG9jYWxob3N0OjMzMDYpLw==
---

apiVersion: v1
kind: Secret
metadata:
  name: prometheus.grafana.admin
  namespace: monitoring
type: Opaque
data:
  username: YWRtaW4=
  password: NDY1NGV6dlRuaVNSSGg=
