---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-conf
  labels:
    app: prometheus
    component: prometheus
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/prometheus/snmp-exporter/conf
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-conf
  namespace: monitoring
  labels:
    app: prometheus
    component: prometheus
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: prometheus-conf
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
  labels:
    app: prometheus-snmp-exporter
    component: snmp-exporter
spec:
  selector:
    app: prometheus
    component: snmp-exporter
  ports:
    - name: http
      port: 9116
      targetPort: 9116
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.44
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-snmp-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      component: snmp-exporter
  template:
    metadata:
      labels:
        app: prometheus
        component: snmp-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /snmp
        prometheus.io/port: '9116'
    spec:
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: prometheus-conf
      containers:
        - name: snmp-exporter
          image: prom/snmp-exporter:v0.14.0
          args:
            - --snmp.wrap-large-counters
            - --config.file=/conf/snmp.yml
          volumeMounts:
            - name: conf
              mountPath: /conf
