bases:
  - ../../../components/nextcloud
  - ../../../components/mariadb
  - ../../../components/redis
patchesStrategicMerge:
  - patches/nextcloud.yaml
  - patches/nextcloud_mariadb.yaml
  - patches/nextcloud_redis.yaml
  - patches/mariadb.yaml
  - patches/nextcloud_node_port.yaml
namePrefix: nextcloud-
commonLabels:
  app: nextcloud
images:
  - name: nextcloud
    newName: nextcloud
    newTag: 16.0.3-apache
  - name: mariadb
    newName: mariadb
    newTag: 10.4.6-bionic
  - name: redis
    newName: redis
    newTag: 5.0.5-alpine
secretGenerator:
  - name: bucket
    literals:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=AdminKey
      - MYSQL_ROOT_PASSWORD=RootKey
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=NextcloudKey
generatorOptions:
  labels:
    component: nextcloud
vars:
  - name: MARIADB_SERVICE
    objref:
      kind: Service
      name: mariadb
      apiVersion: v1
  - name: REDIS_SERVICE
    objref:
      kind: Service
      name: redis
      apiVersion: v1
  - name: NEXTCLOUD_SERVICE_IP
    objref:
      kind: Service
      name: nextcloud
      apiVersion: v1
    fieldref:
      fieldpath: spec.loadBalancerIP
