apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    component: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      component: home-assistant
  template:
    metadata:
      labels:
        component: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: home-assistant
        ports:
        - containerPort: 8123
