---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: snips-assistant
  labels:
    app: snips
    component: snips
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/snips/snips/assistant
    server: proxmox.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snips-assistant
  labels:
    app: snips
    component: snips
    tier: storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: snips-assistant
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snips
  labels:
    app: snips
    component: snips
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snips
      component: snips
      tier: backend
  template:
    metadata:
      labels:
        app: snips
        component: snips
        tier: backend
    spec:
      volumes:
      - name: assistant
        persistentVolumeClaim:
          claimName: snips-assistant
      containers:
      - name: snips-asr
        image: zdock/snips-asr:0.61.1
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: "home-assistant-mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: password
        volumeMounts:
        - name: assistant
          mountPath: /assistant
      - name: snips-tts
        image: zdock/snips-tts:0.61.1
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: "home-assistant-mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: password
        volumeMounts:
        - name: assistant
          mountPath: /assistant
      - name: snips-hotword
        image: zdock/snips-hotword:0.61.1
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: "home-assistant-mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: password
        volumeMounts:
        - name: assistant
          mountPath: /assistant
      - name: snips-nlu
        image: zdock/snips-nlu:0.61.1
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: "home-assistant-mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: password
        volumeMounts:
        - name: assistant
          mountPath: /assistant
      - name: snips-dialogue
        image: zdock/snips-dialogue:0.61.1
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST
          value: "home-assistant-mosquitto"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snips.mqtt.user
              key: password
        volumeMounts:
        - name: assistant
          mountPath: /assistant
