apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    component: nextcloud
spec:
  replicas: 1
  selector:
      matchLabels:
        component: nextcloud
  template:
    metadata:
      labels:
        component: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud-apache
          ports:
            - containerPort: 80
