apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: bitwarden-jz-c-org
  namespace: default
  annotations:
    domain: bitwarden.jz-c.org
spec:
  secretName: production-bitwarden-jz-c-org-tls
  commonName: bitwarden.jz-c.org
  dnsNames:
  - bitwarden.jz-c.org
  issuerRef:
    name: production-letsencrypt
    kind: ClusterIssuer
