apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
  labels:
    component: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      component: bitwarden
  template:
    metadata:
      labels:
        component: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: bitwarden
        env:
        - name: WEBSOCKET_ENABLED
          value: "true"
        ports:
        - containerPort: 80
        - containerPort: 3012
