apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  labels:
    component: bitwarden
spec:
  selector:
    component: bitwarden
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden-websocket
  labels:
    component: bitwarden
spec:
  selector:
    component: bitwarden
  ports:
  - name: websocket
    protocol: TCP
    port: 3012
    targetPort: 3012
