---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvheadend-config
  labels:
    app: tvheadend
    component: tvheadend
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/tvheadend/tvheadend/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tvheadend-recordings
  labels:
    app: tvheadend
    component: tvheadend
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_1tb/k8s/volumes/tvheadend/tvheadend/recordings
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvheadend-config
  labels:
    app: tvheadend
    component: tvheadend
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: tvheadend-config
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tvheadend-recordings
  labels:
    app: tvheadend
    component: tvheadend
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: tvheadend-recordings
---

apiVersion: v1
kind: Service
metadata:
  name: tvheadend
  labels:
    app: tvheadend
    component: tvheadend
    tier: frontend
spec:
  selector:
    app: tvheadend
    component: tvheadend
    tier: frontend
  ports:
    - name: p1
      protocol: TCP
      port: 9981
      targetPort: 9981
    - name: p2
      protocol: TCP
      port: 9982
      targetPort: 9982
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.8
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvheadend
  labels:
    app: tvheadend
    component: tvheadend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tvheadend
      component: tvheadend
      tier: frontend
  template:
    metadata:
      labels:
        app: tvheadend
        component: tvheadend
        tier: frontend
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tvheadend-config
        - name: recordings
          persistentVolumeClaim:
            claimName: tvheadend-recordings
      containers:
        - image: linuxserver/tvheadend:179
          name: tvheadend
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: PGID
              value: "911"
            - name: PUID
              value: "911"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: recordings
              mountPath: /recordings
          ports:
            - containerPort: 9981
            - containerPort: 9982
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
