---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-data
  labels:
    app: bitwarden
    component: bitwarden
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/bitwarden/bitwarden/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-data
  labels:
    app: bitwarden
    component: bitwarden
    tier: storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: bitwarden-data
---

apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  labels:
    app: bitwarden
    component: bitwarden
    tier: frontend
spec:
  selector:
    app: bitwarden
    component: bitwarden
    tier: frontend
  ports:
    - name: php-fpm
      protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
  labels:
    app: bitwarden
    component: bitwarden
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
      component: bitwarden
      tier: frontend
  template:
    metadata:
      labels:
        app: bitwarden
        component: bitwarden
        tier: frontend
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bitwarden-data
      containers:
        - image: mprasil/bitwarden:1.7.0-alpine
          name: bitwarden
          env:
            - name: DOMAIN
              value: https://bitwarden.jz-c.org
            - name: SIGNUPS_ALLOWED
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
