---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-data
  labels:
    app: gogs
    component: gogs
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/gogs/gogs/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-data
  labels:
    app: gogs
    component: gogs
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: gogs-data
---

apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    app: gogs
    component: gogs
    tier: frontend
spec:
  selector:
    app: gogs
    component: gogs
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.245
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
  labels:
    app: gogs
    component: gogs
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
      component: gogs
      tier: frontend
  template:
    metadata:
      labels:
        app: gogs
        component: gogs
        tier: frontend
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gogs-data
      containers:
        - image: "gogs/gogs:0.11.34"
          name: gogs
          ports:
            - containerPort: 22
            - containerPort: 3000
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
