---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-mariadb
  labels:
    app: gogs
    component: mariadb
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/gogs/mariadb
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-mariadb
  labels:
    app: gogs
    component: mariadb
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: gogs-mariadb
---

apiVersion: v1
kind: Service
metadata:
  name: gogs-mariadb
  labels:
    app: gogs
    component: mariadb
    tier: database
spec:
  selector:
    app: gogs
    component: mariadb
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs-mariadb
  labels:
    app: gogs
    component: mariadb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
      component: mariadb
      tier: database
  template:
    metadata:
      labels:
        app: gogs
        component: mariadb
        tier: database
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gogs-mariadb
      containers:
        - name: gogs-mariadb
          image: mariadb:10.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: jk7h54kl5j7h34kl75jh
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
