---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: traccar-mariadb-data
  labels:
    app: traccar
    component: mariadb
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/traccar/mariadb/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traccar-mariadb-data
  labels:
    app: traccar
    component: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: traccar-mariadb-data
---

apiVersion: v1
kind: Service
metadata:
  name: traccar-mariadb
  labels:
    app: traccar
    component: mariadb
spec:
  selector:
    app: traccar
    component: mariadb
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traccar-mariadb
  labels:
    app: traccar
    component: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traccar
      component: mariadb
  template:
    metadata:
      labels:
        app: traccar
        component: mariadb
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: traccar-mariadb-data
      containers:
        - name: mariadb
          image: mariadb:10.3.6
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: traccar.mariadb
                  key: root-password
            - name: MYSQL_DATABASE
              value: traccar
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: traccar.mariadb
                  key: traccar-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: traccar.mariadb
                  key: traccar-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
