apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    component: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      component: influxdb
  template:
    metadata:
      labels:
        component: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        ports:
        - containerPort: 8083
        - containerPort: 8086
