apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    component: influxdb
spec:
  selector:
    component: influxdb
  ports:
  - name: http-api
    protocol: TCP
    port: 8086
    targetPort: 8086
