apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: node-red-data
