apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/home-assistant/node-red/data
    server: proxmox.zhc.x64.me
