apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 64512
      peer-asn: 65530
      peer-address: 192.168.1.1
    address-pools:
    - name: bgp-pool
      protocol: bgp
      addresses:
      - 192.168.70.0/24
