bases:
- ../base
resources:
- resources/certificate.yaml
- resources/ingress.yaml
patchesStrategicMerge:
- patches/set_nextcloud_trusted_domain.yaml
namePrefix: testing-nextcloud-
commonLabels:
  app: nextcloud
  env: testing
images:
- name: nextcloud-fpm
  newName: nextcloud
  newTag: 16.0.3-fpm-alpine
- name: mariadb
  newName: mariadb
  newTag: 10.4.6-bionic
- name: redis
  newName: redis
  newTag: 5.0.5-alpine
- name: nginx
  newName: nginx
  newTag: 1.17.1-alpine
secretGenerator:
- name: bucket
  literals:
  - NEXTCLOUD_ADMIN_USER=admin
  - NEXTCLOUD_ADMIN_PASSWORD=AdminKey
  - MYSQL_ROOT_PASSWORD=RootKey
  - MYSQL_DATABASE=nextcloud
  - MYSQL_USER=nextcloud
  - MYSQL_PASSWORD=NextcloudKey
generatorOptions:
  labels:
    component: nextcloud
vars:
- name: NEXTCLOUD_INGRESS_DOMAIN
  objref:
    kind: Certificate
    name: test-jz-c-org
    apiVersion: certmanager.k8s.io/v1alpha1
  fieldref:
    fieldpath: metadata.annotations.domain
