apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
      component: nextcloud
spec:
  selector:
      component: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
