---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-esphomeyaml
  labels:
    app: home-assistant
    component: esphomeyaml
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/home-assistant/esphomeyaml
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-esphomeyaml
  labels:
    app: home-assistant
    component: esphomeyaml
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-esphomeyaml
---

kind: Service
apiVersion: v1
metadata:
  name: home-assistant-esphomeyaml
  labels:
    app: home-assistant
    component: esphomeyaml
    tier: frontend
spec:
  selector:
    app: home-assistant
    component: esphomeyaml
    tier: frontend
  ports:
  - name: dashboard
    protocol: TCP
    port: 80
    targetPort: 6052
  - name: ota
    protocol: TCP
    port: 6123
    targetPort: 6123
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.1.224
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-esphomeyaml
  labels:
    app: home-assistant
    component: esphomeyaml
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
      component: esphomeyaml
      tier: frontend
  template:
    metadata:
      labels:
        app: home-assistant
        component: esphomeyaml
        tier: frontend
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-esphomeyaml
      containers:
      - name: home-assistant
        image: ottowinter/esphomeyaml:v1.10.1
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 6052
        - containerPort: 6123
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
