---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
  labels:
    app: home-assistant
    component: home-assistant
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/home-assistant/home-assistant/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  labels:
    app: home-assistant
    component: home-assistant
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-config
---

apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
    component: home-assistant
    tier: frontend
spec:
  selector:
    app: home-assistant
    component: home-assistant
    tier: frontend
  ports:
  - name: web-interface
    protocol: TCP
    port: 8123
    targetPort: 8123
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
    component: home-assistant
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
      component: home-assistant
      tier: frontend
  template:
    metadata:
      labels:
        app: home-assistant
        component: home-assistant
        tier: frontend
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-config
      initContainers:
      - name: init-mariadb
        image: mariadb:10.4.1-bionic
        command: ["sh", "-c", "until mysql -h home-assistant-mariadb -u $DATABASE_USER --password=$DATABASE_PASSWORD -e 'SELECT 1'; do echo waiting for home-assistant-mariadb; sleep 2; done;"]
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: home-assistant-mariadb-homeassistant-user
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: home-assistant-mariadb-homeassistant-user
              key: password
      - name: init-influxdb
        image: appropriate/curl
        command: ["sh", "-c", "until curl -sL -I home-assistant-influxdb:8086/ping; do echo waiting for home-assistant-influxdb; sleep 2; done;"]
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:0.88.1
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 8123
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
