---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config
  labels:
    app: home-assistant
    component: home-assistant
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/home-assistant/home-assistant/config
    server: proxmox.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  labels:
    app: home-assistant
    component: home-assistant
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-config
---

apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
    component: home-assistant
    tier: frontend
spec:
  selector:
    app: home-assistant
    component: home-assistant
    tier: frontend
  ports:
  - name: web-interface
    protocol: TCP
    port: 8123
    targetPort: 8123
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
    component: home-assistant
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
      component: home-assistant
      tier: frontend
  template:
    metadata:
      labels:
        app: home-assistant
        component: home-assistant
        tier: frontend
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-config
      initContainers:
      - name: init-influxdb
        image: appropriate/curl
        command: ["sh", "-c", "until curl -sL -I home-assistant-influxdb:8086/ping; do echo waiting for home-assistant-influxdb; sleep 2; done;"]
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:0.96.2
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 8123
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "125m"
            memory: "128Mi"
