---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-mosquitto-config
  labels:
    app: home-assistant
    component: mosquitto
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/home-assistant/mosquitto/mosquitto/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-mosquitto-data
  labels:
    app: home-assistant
    component: mosquitto
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/home-assistant/mosquitto/mosquitto/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-mosquitto-config
  labels:
    app: home-assistant
    component: mosquitto
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-mosquitto-config
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-mosquitto-data
  labels:
    app: home-assistant
    component: mosquitto
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-mosquitto-data
---

kind: Service
apiVersion: v1
metadata:
  name: home-assistant-mosquitto
  labels:
    app: home-assistant
    component: mosquitto
    tier: broker
spec:
  selector:
    app: home-assistant
    component: mosquitto
    tier: broker
  ports:
  - name: unencrypted
    protocol: TCP
    port: 1883
    targetPort: 1883
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: home-assistant-mosquitto
  labels:
    app: home-assistant
    component: mosquitto
    tier: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
      component: mosquitto
      tier: broker
  template:
    metadata:
      labels:
        app: home-assistant
        component: mosquitto
        tier: broker
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-mosquitto-config
      - name: data
        persistentVolumeClaim:
          claimName: home-assistant-mosquitto-data
      containers:
      - name: home-assistant-mosquitto
        image: eclipse-mosquitto:1.4.12
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config
        - name: data
          mountPath: /mosquitto/data
        ports:
        - containerPort: 1883
        - containerPort: 8883
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
