---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-node-red-data
  labels:
    app: home-assistant
    component: home-assistant
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/volumes/home-assistant/node-red/data
    server: proxmox.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-node-red-data
  labels:
    app: home-assistant
    component: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-node-red-data
---

apiVersion: v1
kind: Service
metadata:
  name: home-assistant-node-red
  labels:
    app: home-assistant
    component: node-red
spec:
  selector:
    app: home-assistant
    component: node-red
  ports:
  - name: web-interface
    protocol: TCP
    port: 80
    targetPort: 1880
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.70.14
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-node-red
  labels:
    app: home-assistant
    component: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
      component: node-red
  template:
    metadata:
      labels:
        app: home-assistant
        component: node-red
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: home-assistant-node-red-data
      containers:
      - name: node-red
        image: nodered/node-red-docker:0.20.5-v8
        env:
        - name: TZ
          value: "Europe/Berlin"
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 1880
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
