---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ddclient-config
  labels:
    app: ddclient
    component: ddclient
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/k8s/volumes/ddclient/config
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddclient-config
  labels:
    app: ddclient
    component: ddclient
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: ddclient-config
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddclient
  labels:
    app: ddclient
    component: ddclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddclient
      component: ddclient
  template:
    metadata:
      labels:
        app: ddclient
        component: ddclient
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ddclient-config
      containers:
      - name: ddclient
        image: linuxserver/ddclient:145
        env:
        - name: TZ
          value: "Europe/Berlin"
        volumeMounts:
          - name: config
            mountPath: /config
        resources:
          limits:
            cpu: "125m"
            memory: "128Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
