apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mariadb-data
      containers:
      - name: mariadb
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
