apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
      - name: nextcloud
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2"
      - name: nginx
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "125m"
            memory: "256Mi"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cron
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nextcloud-cron
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
      - name: mariadb
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
