resources:
  - resources/home-assistant/deployment.yaml
  - resources/home-assistant/service.yaml
  - resources/node-red/deployment.yaml
  - resources/node-red/service.yaml
  - resources/influxdb/deployment.yaml
  - resources/influxdb/service.yaml
patchesStrategicMerge:
  - patches/add_influxdb.yaml
