apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2"
