apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: apps
          persistentVolumeClaim:
            claimName: apps
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - name: nextcloud
          volumeMounts:
          - name: config
            mountPath: /var/www/html/config
          - name: apps
            mountPath: /var/www/html/custom_apps
          - name: data
            mountPath: /var/www/html/data
