apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  template:
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant-config
      containers:
      - name: home-assistant
        volumeMounts:
        - name: config
          mountPath: /config
