apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
spec:
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: node-red-data
      containers:
      - name: node-red
        volumeMounts:
        - name: data
          mountPath: /data
