apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  template:
    spec:
      containers:
      - name: bitwarden
        env:
        - name: SIGNUPS_ALLOWED
          value: "false"
