apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  template:
    spec:
      containers:
      - name: bitwarden
        env:
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: bucket
              key: SMTP_HOST
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              name: bucket
              key: SMTP_FROM
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: bucket
              key: SMTP_PORT
        - name: SMTP_SSL
          valueFrom:
            secretKeyRef:
              name: bucket
              key: SMTP_SSL
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: bucket
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bucket
              key: SMTP_PASSWORD
