apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
spec:
  template:
    spec:
      containers:
      - name: bitwarden
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
