apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      initContainers:
        - name: init-mariadb
          image: mariadb
          command: ["sh", "-c", "until mysql -h $(MARIADB_SERVICE) -u $MYSQL_USER --password=$MYSQL_PASSWORD -e 'SELECT 1'; do echo waiting for $(MARIADB_SERVICE); sleep 2; done;"]
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: bucket
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bucket
                key: MYSQL_PASSWORD
      containers:
        - name: nextcloud
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              value: "$(MARIADB_SERVICE)"
