apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: data
              mountPath: /var/www/html/data
          env:
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: NEXTCLOUD_ADMIN_PASSWORD
