apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: test-jz-c-org
  namespace: default
  annotations:
    domain: test.jz-c.org
spec:
  secretName: production-test-jz-c-org-tls
  commonName: test.jz-c.org
  dnsNames:
  - test.jz-c.org
  issuerRef:
    name: staging-letsencrypt
    kind: ClusterIssuer
