apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cron
  labels:
    component: cron
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: html
            persistentVolumeClaim:
              claimName: nextcloud-html
          - name: custom-apps
            persistentVolumeClaim:
              claimName: nextcloud-customapps
          - name: config
            persistentVolumeClaim:
              claimName: nextcloud-config
          - name: data
            persistentVolumeClaim:
              claimName: nextcloud-data
          containers:
          - name: nextcloud-cron
            image: nextcloud-fpm
            command: ["su", "-p", "www-data", "-s", "/bin/sh", "-c", "php -f /var/www/html/cron.php"]
            volumeMounts:
            - name: html
              mountPath: /var/www/html
            - name: custom-apps
              mountPath: /var/www/html/custom_apps
            - name: config
              mountPath: /var/www/html/config
            - name: data
              mountPath: /var/www/html/data
          restartPolicy: OnFailure
