apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/testing-volumes/nextcloud-fpm/nextcloud/html
    server: proxmox.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-customapps
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/testing-volumes/nextcloud-fpm/nextcloud/custom_apps
    server: proxmox.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/testing-volumes/nextcloud-fpm/nextcloud/config
    server: proxmox.zhc.x64.me
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
  nfs:
    path: /datacenter_250gb/k8s/testing-volumes/nextcloud-fpm/nextcloud/data
    server: proxmox.zhc.x64.me
