apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-html
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-customapps
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-customapps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-data
