---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/gogs/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: gogs-data-pv
---

apiVersion: v1
kind: Service
metadata:
  name: gogs-service
spec:
  selector:
    app: gogs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: gogs
  name: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      volumes:
        - name: gogs-data-volume
          persistentVolumeClaim:
            claimName: gogs-data-pvc
      containers:
        - image: "gogs/gogs:0.11.34"
          name: gogs
          ports:
            - containerPort: 22
            - containerPort: 3000
          volumeMounts:
            - mountPath: /data
              name: gogs-data-volume
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "125m"
              memory: "128Mi"
