apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbackup
spec:
  template:
    spec:
      containers:
      - name: urbackup
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
