bases:
- ../base
resources:
- resources/certificate.yaml
- resources/ingress.yaml
- resources/nextcloud/persistent_volumes.yaml
- resources/nextcloud/persistent_volume_claims.yaml
- resources/nextcloud/cronjob.yaml
- resources/mariadb/persistent_volumes.yaml
- resources/mariadb/persistent_volume_claims.yaml
- resources/redis/persistent_volumes.yaml
- resources/redis/persistent_volume_claims.yaml
patchesStrategicMerge:
- patches/set_nextcloud_trusted_domain.yaml
- patches/set_resources.yaml
- patches/add_mariadb_volumes.yaml
- patches/add_redis_volumes.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nextcloud
  path: patches/add_nextcloud_volumes.json
namePrefix: production-nextcloud-
commonLabels:
  app: nextcloud
  env: production
images:
- name: nextcloud-fpm
  newName: nextcloud
  newTag: 16.0.3-fpm-alpine
- name: mariadb
  newName: mariadb
  newTag: 10.4.6-bionic
- name: redis
  newName: redis
  newTag: 5.0.5-alpine
- name: nginx
  newName: nginx
  newTag: 1.17.1-alpine
secretGenerator:
- name: bucket
  envs:
  - ../../../secrets/production-nextcloud.env
generatorOptions:
  labels:
    component: nextcloud
vars:
- name: NEXTCLOUD_INGRESS_DOMAIN
  objref:
    kind: Certificate
    name: test-jz-c-org
    apiVersion: certmanager.k8s.io/v1alpha1
  fieldref:
    fieldpath: metadata.annotations.domain
