---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasmoadmin-data
  labels:
    app: tasmoadmin
    component: tasmoadmin
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/tasmoadmin/tasmoadmin/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasmoadmin-data
  labels:
    app: tasmoadmin
    component: tasmoadmin
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: tasmoadmin-data
---

apiVersion: v1
kind: Service
metadata:
  name: tasmoadmin
  labels:
    app: tasmoadmin
    component: tasmoadmin
    tier: frontend
spec:
  selector:
    app: tasmoadmin
    component: tasmoadmin
    tier: frontend
  ports:
  - name: web-interface
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.247
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tasmoadmin
  labels:
    app: tasmoadmin
    component: tasmoadmin
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasmoadmin
      component: tasmoadmin
      tier: frontend
  template:
    metadata:
      labels:
        app: tasmoadmin
        component: tasmoadmin
        tier: frontend
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tasmoadmin-data
      containers:
      - name: tasmoadmin
        image: raymondmm/tasmoadmin:v1.6.0
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "125m"
            memory: "128Mi"
