---

apiVersion: v1
kind: Service
metadata:
  name: collabora-service
spec:
  selector:
    app: collabora
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9980
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: collabora
  labels:
    app: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
      - name: collabora
        image: collabora/code:3.0.0.5
        env:
        - name: domain
          value: "nextcloud\\.jz-c\\.org|test\\.jz-c\\.org"
        ports:
        - containerPort: 9980
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
