---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-elasticsearch-data
  labels:
    app: nextcloud
    component: elasticsearch
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/nextcloud/elasticsearch/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-elasticsearch-plugins
  labels:
    app: nextcloud
    component: elasticsearch
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/nextcloud/elasticsearch/plugins
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-elasticsearch-data
  labels:
    app: nextcloud
    component: elasticsearch
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-elasticsearch-data
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-elasticsearch-plugins
  labels:
    app: nextcloud
    component: elasticsearch
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-elasticsearch-plugins
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-elasticsearch
  labels:
    app: nextcloud
    component: elasticsearch
    tier: database
spec:
  selector:
    app: nextcloud
    component: elasticsearch
    tier: database
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nextcloud-elasticsearch
  labels:
    app: nextcloud
    component: elasticsearch
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: elasticsearch
      tier: database
  template:
    metadata:
      labels:
        app: nextcloud
        component: elasticsearch
        tier: database
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-elasticsearch-data
        - name: plugins
          persistentVolumeClaim:
            claimName: nextcloud-elasticsearch-plugins
      containers:
        - name: nextcloud-elasticsearch
          image: elasticsearch:5.6.9
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms768m -Xmx768m"
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
            - name: plugins
              mountPath: /usr/share/elasticsearch/plugins
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            limits:
              cpu: "250m"
              memory: "1Gi"
            requests:
              cpu: "125m"
              memory: "128Mi"
