---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
  labels:
    app: nextcloud
    component: nextcloud
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/nextcloud/nextcloud/html
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  labels:
    app: nextcloud
    component: nextcloud
    tier: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_1tb/kubernetes/production/persistent_volumes_manual/nextcloud/nextcloud/data
    server: storage.zcc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html
  labels:
    app: nextcloud
    component: nextcloud
    tier: storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-html
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  labels:
    app: nextcloud
    component: nextcloud
    tier: storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-data
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-php-fpm
  labels:
    app: nextcloud
    component: nextcloud
    tier: data
data:
  www.conf: |
    [www]
    user = www-data
    group = www-data

    listen = 127.0.0.1:9000

    pm = dynamic
    pm.max_children = 20
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-fpm
  labels:
    app: nextcloud
    component: nextcloud
    tier: frontend
spec:
  selector:
    app: nextcloud
    component: nextcloud
    tier: frontend
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
    component: nextcloud
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      component: nextcloud
      tier: frontend
  template:
    metadata:
      labels:
        app: nextcloud
        component: nextcloud
        tier: frontend
    spec:
      volumes:
        - name: php-fpm
          configMap:
            name: nextcloud-php-fpm
        - name: html
          persistentVolumeClaim:
            claimName: nextcloud-html
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data
      containers:
        - image: nextcloud:14.0.1-fpm
          name: nextcloud
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-nextcloud-user
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mariadb-nextcloud-user
                  key: password
            - name: MYSQL_HOST
              value: nextcloud-mariadb-service
            - name: NEXTCLOUD_TABLE_PREFIX
              value: "oc_"
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "75J)Fb.a"
          volumeMounts:
            - name: php-fpm
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: html
              mountPath: /var/www/html
            - name: data
              mountPath: /var/www/html/data
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cron
  labels:
    app: nextcloud
    component: nextcloud-cron
    tier: frontend
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: nextcloud
        component: nextcloud-cron
        tier: frontend
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 33
          volumes:
            - name: html
              persistentVolumeClaim:
                claimName: nextcloud-html
            - name: data
              persistentVolumeClaim:
                claimName: nextcloud-data
          containers:
          - name: nextcloud-cron
            image: nextcloud:14.0.1-fpm
            command: ["php"]
            args:
              - -f
              - /var/www/html/cron.php
            volumeMounts:
              - name: html
                mountPath: /var/www/html
              - name: data
                mountPath: /var/www/html/data
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: OnFailure
# ---
#
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: nextcloud-preview-cron
#   labels:
#    app: nextcloud
#    component: nextcloud-preview-cron
#    tier: frontend
# spec:
#   schedule: "*/30 * * * *"
#   jobTemplate:
#     metadata:
#       labels:
#         app: nextcloud
#         component: nextcloud-preview-cron
#         tier: frontend
#     spec:
#       template:
#         metadata:
#           labels:
#             app: nextcloud
#             component: nextcloud-preview-cron
#             tier: frontend
#         spec:
#           securityContext:
#             runAsUser: 33
#           volumes:
#             - name: html
#               persistentVolumeClaim:
#                 claimName: nextcloud-html
#             - name: data
#               persistentVolumeClaim:
#                 claimName: nextcloud-data
#           containers:
#           - name: nextcloud-preview-cron
#             image: nextcloud:14.0.1-fpm
#             command: ["php"]
#             args:
#               - /var/www/html/occ
#               - preview:pre-generate
#             volumeMounts:
#               - name: html
#                 mountPath: /var/www/html
#               - name: data
#                 mountPath: /var/www/html/data
#             resources:
#               requests:
#                 memory: "128Mi"
#                 cpu: "250m"
#               limits:
#                 memory: "512Mi"
#                 cpu: "500m"
#           restartPolicy: Never
# ---
#
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: nextcloud-generate-all-previews
#   labels:
#    app: nextcloud
#    component: nextcloud-generate-all-previews
#    tier: frontend
# spec:
#   backoffLimit: 5
#   template:
#     spec:
#       securityContext:
#         runAsUser: 33
#       volumes:
#         - name: html
#           persistentVolumeClaim:
#             claimName: nextcloud-html
#         - name: data
#           persistentVolumeClaim:
#             claimName: nextcloud-data
#       containers:
#       - name: nextcloud-preview-cron
#         image: nextcloud:14.0.1-fpm
#         command: ["php"]
#         args:
#           - /var/www/html/occ
#           - preview:generate-all
#         volumeMounts:
#           - name: html
#             mountPath: /var/www/html
#           - name: data
#             mountPath: /var/www/html/data
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "250m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
#       restartPolicy: Never
# ---
#
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: nextcloud-index
#   labels:
#    app: nextcloud
#    component: nextcloud-index
#    tier: frontend
# spec:
#   backoffLimit: 5
#   template:
#     spec:
#       securityContext:
#         runAsUser: 33
#       volumes:
#         - name: nextcloud-html-volume
#           persistentVolumeClaim:
#             claimName: nextcloud-html-pvc
#         - name: nextcloud-data-volume
#           persistentVolumeClaim:
#             claimName: nextcloud-data-pvc
#       containers:
#       - name: nextcloud-preview-cron
#         image: nextcloud:14.0.1-fpm
#         command: ["php"]
#         args:
#           - /var/www/html/occ
#           - fulltextsearch:index
#         env:
#           - name: MYSQL_DATABASE
#             value: nextcloud
#           - name: MYSQL_USER
#             value: nextcloud
#           - name: MYSQL_PASSWORD
#             value: ß1046ß23863205671
#           - name: MYSQL_HOST
#             value: nextcloud-mariadb-service
#           - name: NEXTCLOUD_TABLE_PREFIX
#             value: "oc_"
#           - name: NEXTCLOUD_ADMIN_USER
#             value: admin
#           - name: NEXTCLOUD_ADMIN_PASSWORD
#             value: "75J)Fb.a"
#         volumeMounts:
#           - name: nextcloud-html-volume
#             mountPath: /var/www/html
#           - name: nextcloud-data-volume
#             mountPath: /var/www/html/data
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "250m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
#       restartPolicy: Never
