---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/nextcloud/html
    server: storage.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_1tb/kubernetes/production/persistent_volumes_manual/nextcloud/data
    server: storage.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-html-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-html-pv
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-data-pv
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-fpm
spec:
  selector:
    app: nextcloud
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-html-volume
          persistentVolumeClaim:
            claimName: nextcloud-html-pvc
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
      containers:
        - image: nextcloud:13.0.1-fpm
          name: nextcloud
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: ß1046ß23863205671
            - name: MYSQL_HOST
              value: nextcloud-mariadb-service
            - name: NEXTCLOUD_TABLE_PREFIX
              value: "oc_"
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "75J)Fb.a"
          volumeMounts:
            - name: nextcloud-html-volume
              mountPath: /var/www/html
            - name: nextcloud-data-volume
              mountPath: /var/www/html/data
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-cron
  labels:
    app: nextcloud-cron
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: nextcloud-cron
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 33
          volumes:
            - name: nextcloud-html-volume
              persistentVolumeClaim:
                claimName: nextcloud-html-pvc
            - name: nextcloud-data-volume
              persistentVolumeClaim:
                claimName: nextcloud-data-pvc
          containers:
          - name: nextcloud-cron
            image: nextcloud:13.0.1-fpm
            command: ["php"]
            args:
              - -f
              - /var/www/html/cron.php
            volumeMounts:
              - name: nextcloud-html-volume
                mountPath: /var/www/html
              - name: nextcloud-data-volume
                mountPath: /var/www/html/data
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: OnFailure
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nextcloud-preview-cron
  labels:
    app: nextcloud-preview-cron
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: nextcloud-preview-cron
    spec:
      template:
        metadata:
          labels:
            app: nextcloud-preview-cron
        spec:
          securityContext:
            runAsUser: 33
          volumes:
            - name: nextcloud-html-volume
              persistentVolumeClaim:
                claimName: nextcloud-html-pvc
            - name: nextcloud-data-volume
              persistentVolumeClaim:
                claimName: nextcloud-data-pvc
          containers:
          - name: nextcloud-preview-cron
            image: nextcloud:13.0.1-fpm
            command: ["php"]
            args:
              - /var/www/html/occ
              - preview:pre-generate
            volumeMounts:
              - name: nextcloud-html-volume
                mountPath: /var/www/html
              - name: nextcloud-data-volume
                mountPath: /var/www/html/data
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: Never
# ---
#
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: nextcloud-generate-all-previews
# spec:
#   backoffLimit: 5
#   template:
#     spec:
#       securityContext:
#         runAsUser: 33
#       volumes:
#         - name: nextcloud-html-volume
#           persistentVolumeClaim:
#             claimName: nextcloud-html-pvc
#         - name: nextcloud-data-volume
#           persistentVolumeClaim:
#             claimName: nextcloud-data-pvc
#       containers:
#       - name: nextcloud-preview-cron
#         image: nextcloud:13.0.1-fpm
#         command: ["php"]
#         args:
#           - /var/www/html/occ
#           - preview:generate-all
#         volumeMounts:
#           - name: nextcloud-html-volume
#             mountPath: /var/www/html
#           - name: nextcloud-data-volume
#             mountPath: /var/www/html/data
#         resources:
#           requests:
#             memory: "128Mi"
#             cpu: "250m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
#       restartPolicy: Never
