---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/nextcloud/config
    server: storage.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_1tb/kubernetes/production/persistent_volumes_manual/nextcloud/data
    server: storage.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-config-pv
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-data-pv
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      volumes:
        - name: nextcloud-config-volume
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
        - name: nextcloud-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
      containers:
        - image: linuxserver/nextcloud:113
          name: nextcloud
          volumeMounts:
            - mountPath: /config
              name: nextcloud-config-volume
            - mountPath: /data
              name: nextcloud-data-volume
          ports:
            - containerPort: 443
