---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=3
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent_volumes_manual/nextcloud/redis/data
    server: storage.zhc.x64.me
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: nextcloud-redis-data-pv
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud-redis-service
spec:
  selector:
    app: nextcloud-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: nextcloud-redis
  name: nextcloud-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-redis
  template:
    metadata:
      labels:
        app: nextcloud-redis
    spec:
      volumes:
        - name: nextcloud-redis-data-volume
          persistentVolumeClaim:
            claimName: nextcloud-redis-data-pvc
      containers:
        - image: redis:4.0.8-alpine
          name: nextcloud-redis
          volumeMounts:
            - mountPath: /data
              name: nextcloud-redis-data-volume
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
