---

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-user
type: Opaque
data:
  username: YWRtaW4K
  password: NzVKKUZiLmEK

---

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mariadb-root-user
type: Opaque
data:
  username: cm9vdAo=
  password: MDE5MjgzNzVqazFoNTEyNQo=
---

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-mariadb-nextcloud-user
type: Opaque
data:
  username: bmV4dGNsb3VkCg==
  password: w58xMDQ2w58yMzg2MzIwNTY3MQo=
