bases:
  - ../bases
resources:
  - resources/ingress.yaml
patchesStrategicMerge:
  - patches/domain.yaml
  - patches/volumes.yaml
namePrefix: testing-nextcloud
commonLabels:
  app: nextcloud
  env: testing
images:
  - name: nextcloud-apache
    newName: nextcloud
    newTag: 16.0.3-apache
  - name: mariadb
    newName: mariadb
    newTag: 10.4.6-bionic
  - name: redis
    newName: redis
    newTag: 5.0.5-alpine
secretGenerator:
  - name: bucket
    literals:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=AdminKey
      - MYSQL_ROOT_PASSWORD=RootKey
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=NextcloudKey
generatorOptions:
  labels:
    component: nextcloud
vars:
  - name: NEXTCLOUD_INGRESS_DOMAIN
    objref:
      kind: Ingress
      name: nextcloud
      apiVersion: networking.k8s.io/v1beta1
    fieldref:
      fieldpath: metadata.annotations.domain
